server:
  port: 8068
spring:
  application.name: ledgers-idp
  datasource:
    username: cms
    password: cms
    url: jdbc:postgresql://localhost:5432/consent?currentSchema=idp
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: idp
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"
      cors:
        allow-credentials: true
        allowed-origins: "*"
        allowed-headers: Access-Control-Allow-Headers, Content-Type, Origin, X-Requested-With, Cookie, Authorization
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
        max-age: 3600
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  health:
    mail:
      enabled: false
idp:
  default:
    token:
      lifetime:
        seconds: 100000

  jwt:
    hs256:
      secret: 6VFX8YFQG5DLFKZIMNLGH9P406XR1SY4